### PR TITLE
Added tests for db and app

### PR DESCRIPTION
**Pull request by emilyllim**
The following tests are added:
Database:
- Create first timeline post and check that its id is equal to 1.
- Create second timeline post and check that its id is equal to 2.
- Create two timeline posts and get all posts in the db. Each id should increase by 1.

App:
- Get home page and check that the status code is 200.
- The title text "EMILIE ZHANG" is present in the HTML.
- The image "./static/img/emilie.png" is present in the HTML.
- Get timeline_post JSON page and check that the status code is 200.
- The data is JSON.
- "timeline_posts" exists in the JSON.
- "timeline_posts" is initially empty.
- Post request with name, email, and content results in JSON length of 1.
- Get timeline page and check for "TIMELINE" title text and Submit button in HTML.
- Missing name in POST request results in 400 status code and "Invalid name" message.
- Empty content in POST request results in 400 status code and "Invalid content" message.
- Malformed email in POST request results in 400 status code and "Invalid email" message.

### CODE REVIEW

**Review by EmilieYZhang — CHANGES_REQUESTED** [review]
Would you be able to add one more invalid input test case? One that checks the 'name' input is not an empty string. Everything else looks good, and the test cases all pass!

**Review by EmilieYZhang — COMMENTED** [review]
Afterwards, will be ready to merge!

**Comment by emilyllim** [comment]
In test_db.py, I added a separate function for getting posts called test_timeline_get, but I just realized that is unnecessary. You can remove it and just get posts in the test_timeline_post function instead.

**Comment by emilyllim** [comment]
Just added the extra test! It should be good to merge.

**Review by EmilieYZhang — APPROVED** [review]

**Comment by EmilieYZhang** [comment]
Thanks, that looks good! Merging into main.

**Pull request merged**
